Add sold_after and sold_before in ranking API; test cases refactor
likecoin/likecoin-chain-tx-indexer pull request #57
Opened 2022-11-28 10:48 UTC by nnkken

In this PR, `Before` and `After` in ranking API refers to sold time instead of creation time.
The original creation time semantic are moved to `CreatedBefore` and `CreatedAfter` fields.

Also, test cases are refactored (again) so now database data for test cases are created locally in each test case instead of shared globally.
This allows creating test cases easier.

Also added address migration, which includes (a) converting addresses before writing into database; (b) a parallel migration (which takes half a day to finish) for existing data.
Running that is not urgent nor necessary, since most of the queries are querying a set of addresses containing both prefixes. However, some counts may be affected (e.g. duplicate entries in nft count).

Also fixed ~tones~ some of the queries.

2022-11-30 18:37 UTC, williamchong requested changes
Still haven't read nft_test.go yet, will read tmr

2022-11-30 18:37 UTC, williamchong commented on rest/nft.go
> +	DEFAULT_API_ADDRESSES = []string{"like17m4vwrnhjmd20uu7tst7nv0kap6ee7js69jfrs"}
Can this be overide by a env/config? Useful when deploying testnet

2022-11-30 18:37 UTC, williamchong commented on db/schema/parallel.go
> +			batch.Queue(
Can we not update if `convertedOwner === owners[i]`?

2022-12-02 13:13 UTC, williamchong approved these changes

2022-12-02 13:14 UTC, merged

2022-12-02 13:39 UTC, williamchong commented
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/6198816/205305465-9c358d76-4658-4aaf-9a4d-edfa214ce642.png">
Probably should check not empty string for address migration too

2022-12-02 13:44 UTC, nnkken commented
> <img alt="image" width="1212" src="https://user-images.githubusercontent.com/6198816/205305465-9c358d76-4658-4aaf-9a4d-edfa214ce642.png">
> 
> Probably should check not empty string for address migration too

Conversion error is expected, so it's a warning rather than an error