✨ Return `pagination.total` in `/collector` and `/creator` endpoints
likecoin/likecoin-chain-tx-indexer pull request #59
Opened 2022-11-30 05:28 UTC by WeiJun0827

- Add an omissible field `Total` in type `Pagination`.
- Get the total row count from the original query.
- Note that for performance concern, `pagination.total` is acquired from the original query with `OFFSET` but not another aggregation query, it will be `nil` if the given `OFFSET` value is greater than the actual total row count.

2022-11-30 09:16 UTC, nnkken commented
What's the difference between `Count` and `Total`?
My understanding is that `Count` means the total number of items returned in the response (with respect to the pagination in the request), while `Total` means the total number of items in the database matching the request conditions (ignoring the pagination in the request).
i.e. if the database has 100 NFTs, then querying NFTs with pagination { limit = 10 } returns { NFTs: [...], Count: 10, Total: 100 }.
But the behavior in this PR seems to use `Total` as what I understand as `Count`? Then what is the `Count` field for?

2022-11-30 09:27 UTC, nnkken commented
Hmm tried the query and found that `row_count` is actually what I understand as `Total`, it seems I misunderstood how `OVER` works...

2022-11-30 09:29 UTC, nnkken approved these changes

2022-11-30 14:52 UTC, williamchong requested changes

2022-11-30 14:52 UTC, williamchong commented on db/nft.go
> +		logger.L.Errorw("ailed to query creators", "error", err, "q", q)
```suggestion
		logger.L.Errorw("failed to query creators", "error", err, "q", q)
```

2022-12-01 06:41 UTC, williamchong approved these changes

2022-12-01 08:11 UTC, merged