Embed class data in NFT query response
likecoin/likecoin-chain-tx-indexer pull request #60
Opened 2022-12-06 07:12 UTC by nnkken

Added full class data in NFT query response, so caller can get class metadata (and other class info) without calling separate APIs.

(for compatibility reason, the `class_parent` field is kept)

Sample query: `/likechain/likenft/v1/nft?owner=like13f4glvg80zvfrrs7utft5p68pct4mcq7t5atf6&pagination.limit=1`

Before:
```JSON
{
  "pagination": { "next_key": 10065, "count": 1 },
  "nfts": [
    {
      "nft_id": "writing-03a4ec69-a339-4d74-a879-0ee140d5f0fe",
      "class_id": "likenft1jvywpl0f0zndhm6h8sp44esaj88mrkew226wv30ymeq5pnvux4tq760qd7",
      "owner": "like13f4glvg80zvfrrs7utft5p68pct4mcq7t5atf6",
      "uri": "https://api.like.co/likernft/metadata?class_id=likenft1jvywpl0f0zndhm6h8sp44esaj88mrkew226wv30ymeq5pnvux4tq760qd7&nft_id=writing-03a4ec69-a339-4d74-a879-0ee140d5f0fe",
      "uri_hash": "",
      "metadata": {
        "name": "Writing NFT - LikeCoin Chain NFT Module Upgrade, StarFerry Overview",
        "image": "ar://-l7lNA57Vi4jKS7GZHWZppsS-ujoZM7PxWYMyQ6hel8"
      },
      "timestamp": "2022-08-01T02:14:57Z",
      "class_parent": {
        "type": "ISCN",
        "iscn_id_prefix": "iscn://likecoin-chain/uioz4L768qWnVId4uGVnzJqVEXWYo9YBVHAftZNjZWk",
        "account": ""
      }
    }
  ]
}
```

After:
```JSON
{
  "pagination": { "next_key": 10065, "count": 1 },
  "nfts": [
    {
      "nft_id": "writing-03a4ec69-a339-4d74-a879-0ee140d5f0fe",
      "class_id": "likenft1jvywpl0f0zndhm6h8sp44esaj88mrkew226wv30ymeq5pnvux4tq760qd7",
      "owner": "like13f4glvg80zvfrrs7utft5p68pct4mcq7t5atf6",
      "uri": "https://api.like.co/likernft/metadata?class_id=likenft1jvywpl0f0zndhm6h8sp44esaj88mrkew226wv30ymeq5pnvux4tq760qd7&nft_id=writing-03a4ec69-a339-4d74-a879-0ee140d5f0fe",
      "uri_hash": "",
      "metadata": {
        "name": "Writing NFT - LikeCoin Chain NFT Module Upgrade, StarFerry Overview",
        "image": "ar://-l7lNA57Vi4jKS7GZHWZppsS-ujoZM7PxWYMyQ6hel8"
      },
      "timestamp": "2022-08-01T02:14:57Z",
      "class_parent": {
        "type": "ISCN",
        "iscn_id_prefix": "iscn://likecoin-chain/uioz4L768qWnVId4uGVnzJqVEXWYo9YBVHAftZNjZWk",
        "account": ""
      },
      "class_data": {
        "id": "likenft1jvywpl0f0zndhm6h8sp44esaj88mrkew226wv30ymeq5pnvux4tq760qd7",
        "name": "Writing NFT - LikeCoin Chain NFT Module Upgrade, StarFerry Overview",
        "description": "The long-awaited NFT module will be the spotlight in the StarFerry upgrade. This upgrade features the nft module, and nft-related services, such as nft minting, blind box, and marketplace chain API.",
        "symbol": "WRITING",
        "uri": "https://api.like.co/likernft/metadata?iscn_id=iscn%3A%2F%2Flikecoin-chain%2Fuioz4L768qWnVId4uGVnzJqVEXWYo9YBVHAftZNjZWk%2F2",
        "uri_hash": "",
        "config": {
          "burnable": false,
          "max_supply": "0",
          "blind_box_config": null
        },
        "metadata": {
          "url": "https://blog.like.co/en/likecoin-chain-upgrade-starferry-overview/",
          "name": "LikeCoin Chain NFT Module Upgrade, StarFerry Overview",
          "@type": "Article",
          "image": "ar://-l7lNA57Vi4jKS7GZHWZppsS-ujoZM7PxWYMyQ6hel8",
          "version": 1,
          "@context": "http://schema.org/",
          "keywords": "Cosmos,IBC,LikeCoin",
          "usageInfo": "",
          "description": "The long-awaited NFT module will be the spotlight in the StarFerry upgrade. This upgrade features the nft module, and nft-related services, such as nft minting, blind box, and marketplace chain API.",
          "nft_meta_collection_id": "likerland_writing_nft",
          "nft_meta_collection_name": "Writing NFT",
          "nft_meta_collection_descrption": "Writing NFT by Liker Land"
        },
        "parent": {
          "type": "ISCN",
          "iscn_id_prefix": "iscn://likecoin-chain/uioz4L768qWnVId4uGVnzJqVEXWYo9YBVHAftZNjZWk",
          "account": ""
        },
        "price": 0,
        "created_at": "2022-07-29T14:58:54Z"
      }
    }
  ]
}
```

2022-12-06 07:15 UTC, WeiJun0827 approved these changes

2022-12-06 07:51 UTC, williamchong requested changes
Can we add a qs for toggling this on/off, default off

2022-12-06 09:59 UTC, nnkken commented
Added `expand_classes` qs

2022-12-06 19:17 UTC, nwingt approved these changes

2022-12-07 05:42 UTC, williamchong approved these changes
@nwingt please confirm this is enough for what you need though

2022-12-07 07:41 UTC, merged