Add marketplace extractor and query
likecoin/likecoin-chain-tx-indexer pull request #64
Opened 2022-12-22 17:21 UTC by nnkken

Query: `/likechain/likenft/v1/marketplace?type={listing|offer}[&class_id=blablabla][&nft_id=blablabla][&creator=blablabla]`
Currently order by expiration, should order by price?

2022-12-22 17:24 UTC, nnkken commented
Changed to order by price instead of expiration.
Turns out doesn't need to change test cases...

2022-12-30 15:03 UTC, williamchong requested changes

2022-12-30 15:03 UTC, williamchong commented on rest/marketplace_test.go
> +			items:  []db.NftMarketplaceItem{marketplaceItems[4]},
nft id should also come with class id for it to be an unique key

2023-01-03 01:31 UTC, nnkken commented on db/schema/v009.sql
> +CREATE INDEX idx_nft_marketplace_nft_id ON nft_marketplace (
For speeding up searches with NFT ID only, not sure if we have this use case, but seems quite natural?

2023-01-03 01:33 UTC, nnkken commented on poller/poller.go
> +	batch.UpdateLatestBlockHeight(maxHeight)
No, extractor runs asynchronously with poller, and they have different "height" (`META_BLOCK_HEIGHT` for poller, `META_EXTRACTOR` for extractor)

2023-01-03 01:34 UTC, nnkken commented on db/marketplace_test.go
> +			items:  []NftMarketplaceItem{marketplaceItems[4]},
So `NFT ID only` is not our use case?

2023-01-04 18:43 UTC, williamchong approved these changes

2023-01-04 18:44 UTC, merged