✨ Allow multiple address query for `GET /event`
likecoin/likecoin-chain-tx-indexer pull request #81
Opened 2023-02-17 14:19 UTC by WeiJun0827

2023-02-20 06:27 UTC, williamchong requested changes
Please add new test case(s) for multiple sender/receiver query

2023-02-21 02:40 UTC, WeiJun0827 commented
<img width="999" alt="截圖 2023-02-18 下午12 27 14" src="https://user-images.githubusercontent.com/33746295/220233515-4a7c5f14-4dd2-43e0-b0c8-cd18c23b392a.png">
Seems GitHub crashed when the last commit was pushed, so it's missing 🌚

2023-02-21 04:03 UTC, nnkken approved these changes

2023-02-21 04:18 UTC, williamchong approved these changes

2023-02-21 05:00 UTC, merged